# Pre-commit hooks for code quality
# Not too strict, focusing on maintainability

repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1000"] # Warn for files > 1MB
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--indent=4"]
      - id: check-toml
      - id: debug-statements # Find forgotten print/pdb statements
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Python code formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=100", "--target-version=py39", "--skip-string-normalization"]

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          [
            "--profile=black",
            "--line-length=100",
            "--multi-line=3",
            "--trailing-comma",
            "--force-grid-wrap=0",
            "--use-parentheses",
            "--ensure-newline-before-comments",
          ]

  # Docstring formatter
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args:
          ["--in-place", "--wrap-summaries=100", "--wrap-descriptions=100", "--pre-summary-newline"]

  # Basic linting with flake8 (includes docstring checks)
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          [
            "--max-line-length=100",
            "--extend-ignore=E203,E266,E501,W503,F403,F401",
            "--max-complexity=15",
            "--exclude=.git,__pycache__,old,build,dist",
            "--docstring-convention=google",
          ]
        additional_dependencies:
          - flake8-docstrings==1.7.0
          - flake8-bugbear==24.1.17
          - flake8-comprehensions

  # Security checks (basic)
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-ll", "-i", "-r", "src/"] # Low severity, only on src/
        exclude: "tests/"

  # YAML/Markdown/JSON formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown]
        args: ["--print-width=100", "--prose-wrap=preserve"]

# Optional: type checking (enable if needed)
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.7.1
#   hooks:
#     - id: mypy
#       args: ['--ignore-missing-imports', '--no-strict-optional']

# Settings
default_language_version:
  python: python3.9

# Don't run on commit messages or tags
default_stages: [commit]

# Allow empty commits (useful for testing)
allow_missing_config: false

# Files to exclude globally
exclude: |
  (?x)^(
    poetry.lock|
    \.git/|
    \.tox/|
    dist/|
    \.eggs/|
    _build/|
    build/|
    migrations/
  )$
